name: Backend CI/CD

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
            - LICENSE


jobs:
    build-production:

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-java@v1
              with:
                java-version: '11'

            - name: Show Java version
              run: java -version

            - name: Show maven version
              run: sudo mvn -v

            - name: Build with Maven
              run: sudo mvn -B package --file pom.xml


            - name: Deploy to Server
              uses: AEnterprise/rsync-deploy@v1.0
              env:
                  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
                  ARGS: -avz --delete --exclude='*.pyc'
                  SERVER_PORT: '22'
                  FOLDER: ./target/real-me-1.0.0-SNAPSHOT-fat.jar
                  SERVER_IP: ${{ secrets.SSH_HOST }}
                  USERNAME: ${{ secrets.SSH_USERNAME }}
                  SERVER_DESTINATION: /root/javabuild/
