name: Backend CI/CD

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
            - LICENSE

jobs:
    build-production:

        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 11
                uses: actions/setup-java@v1
                with:
                    java-version: '11'

            -   name: Build with Maven
                run: mvn package -e -Dmaven.test.skip=true

            -   name: Deploy to Server
                uses: AEnterprise/rsync-deploy@v1.0
                env:
                    DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
                    ARGS: -avz --delete --exclude='*.pyc'
                    SERVER_PORT: '22'
                    FOLDER: ./target/real-me-version-fat.jar
                    SERVER_IP: ${{ secrets.HOST }}
                    USERNAME: ${{ secrets.USERNAME }}
                    SERVER_DESTINATION: /opt/docker_vertx/target/fat.jar

            -   name: executing remote ssh commands using password
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    key: ${{ secrets.DEPLOY_KEY }}
                    port: ${{ secrets.PORT }}
                    script: |
                        cd /opt/docker_vertx/
                        docker-compose restart
