name: Backend CI/CD

on:
    push:
        branches:
            - master
        paths-ignore:
            - README.md
            - LICENSE


jobs:
    build-production:

        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-java@v1
                with:
                java-version: '11' # The JDK version to make available on the path.

#            - name: Use Node.js ${{ matrix.node-version }}
#              uses: actions/setup-node@v1
#              with:
#                  node-version: ${{ matrix.node-version }}
#
#            - name: Install dependencies
#              run: npm install
#
#            - name: Build
#              run: npm run build --if-present

#            - name: Deploy to Server
#              uses: AEnterprise/rsync-deploy@v1.0
#              env:
#                  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
#                  ARGS: -avz --delete --exclude='*.pyc'
#                  SERVER_PORT: '22'
#                  FOLDER: ./build/*
#                  SERVER_IP: ${{ secrets.SSH_HOST }}
#                  USERNAME: ${{ secrets.SSH_USERNAME }}
#                  SERVER_DESTINATION: /root/build/
